USERS_TABLE = 'users'
USER_ID_ENTRY = 'user_id'
EMAIL_ENTRY = 'email'
PW_ENTRY = 'password'
SALT_ENTRY = 'salt'
FILES_DIR_ENTRY = 'files_directory'

CREATE_USERS_TABLE = f"""
CREATE TABLE {USERS_TABLE} (
    {USER_ID_ENTRY} INTEGER PRIMARY KEY AUTOINCREMENT,
    {EMAIL_ENTRY} TEXT UNIQUE NOT NULL,
    {PW_ENTRY} STRING(255) NOT NULL,
    {SALT_ENTRY} VARCHAR(255), 
    {FILES_DIR_ENTRY} TEXT
);
"""

INSERT_USER = f"INSERT INTO {USERS_TABLE} (email, password, salt) VALUES (?, ?, ?);"

SELECT_USER_PW_SALT = f"SELECT {PW_ENTRY}, {SALT_ENTRY} FROM {USERS_TABLE} WHERE {EMAIL_ENTRY} = ?;"

FIND_USER = f"SELECT * FROM {USERS_TABLE} WHERE {EMAIL_ENTRY} = ?;"

SELECT_USER_ID = f"SELECT {USER_ID_ENTRY} FROM {USERS_TABLE} WHERE {EMAIL_ENTRY} = ?;"

SELECT_ALL_USERS = f"SELECT * FROM {USERS_TABLE};"