USERS_TABLE = 'users'
EMAIL_ENTRY = 'email'
PW_ENTRY = 'password'
SALT_ENTRY = 'salt'

CREATE_USERS_TABLE = f"""
CREATE TABLE {USERS_TABLE} (
    {EMAIL_ENTRY} TEXT PRIMARY KEY,
    {PW_ENTRY} STRING(255) NOT NULL,
    {SALT_ENTRY} VARCHAR(255)
);
"""

INSERT_USER = f"INSERT INTO {USERS_TABLE} (email, password, salt) VALUES (?, ?, ?);"

SELECT_USER_PW_SALT = f"SELECT {PW_ENTRY}, {SALT_ENTRY} FROM {USERS_TABLE} WHERE {EMAIL_ENTRY} = ?;"

# SELECT_USER_PW = f"SELECT {PW_ENTRY} FROM {USERS_TABLE} WHERE {EMAIL_ENTRY} = ?;"
# SELECT_USER_SALT = f"SELECT {SALT_ENTRY} FROM {USERS_TABLE} WHERE {EMAIL_ENTRY} = ?;"